config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cart_items, only: [:create, :destroy] # o el método que uses para gestionar el carrito
  get 'cart', to: 'cart_items#index', as: 'cart' # Asegúrate de tener la ruta para mostrar el carrito


  root 'products#index'

  resources :payments
  resources :reviews
  resources :product_promotions
  resources :promotions
  resources :cart_items
  resources :product_categories

  resources :categories

  resources :categories, only: [:create]

  resources :users
  resources :order_items
  resources :orders
  resources :products
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validate :quantity_must_not_exceed_stock

  private

  def quantity_must_not_exceed_stock
    if quantity.present? && quantity > product.stock
      errors.add(:Cantidad, "no puede ser mayor que el stock disponible (#{product.stock})")
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_one :payment
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  has_many :product_promotions
  has_many :promotions, through: :product_promotions
  has_many :reviews
  has_many :cart_items

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  def category_ids=(ids)
    self.product_categories = ids.map { |id| ProductCategory.new(category_id: id) if id.present? }.compact
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_promotion.rb
class ProductPromotion < ApplicationRecord
  belongs_to :product
  belongs_to :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :product_promotions
  has_many :products, through: :product_promotions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :reviews
  has_many :cart_items

  # Roles de usuario
  ROLES = %w[admin registered guest client]

  validates :role, inclusion: { in: ROLES }, allow_nil: true

  # Métodos de conveniencia para verificar el rol
  def admin?
    role == 'admin'
  end

  def registered?
    role == 'registered'
  end

  def guest?
    role == 'guest'
  end

  def client?
    role == 'client'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_path, status: :see_other, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:order_id, :payment_date, :amount, :payment_method, :status)
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :payment_date, style: "display: block" %>
    <%= form.datetime_field :payment_date %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Order:</strong>
    <%= payment.order_id %>
  </p>

  <p>
    <strong>Payment date:</strong>
    <%= payment.payment_date %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= payment.payment_method %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= payment.status %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>