config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :cart_items, only: [:create, :destroy] # o el método que uses para gestionar el carrito
  get 'cart', to: 'cart_items#index', as: 'cart' # Asegúrate de tener la ruta para mostrar el carrito


  root 'products#index'

  resources :payments
  resources :reviews
  resources :product_promotions
  resources :promotions
  resources :cart_items
  resources :product_categories

  resources :categories

  resources :categories, only: [:create]

  resources :users
  resources :order_items
  resources :orders
  resources :products
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validate :quantity_must_not_exceed_stock

  private

  def quantity_must_not_exceed_stock
    if quantity.present? && quantity > product.stock
      errors.add(:Cantidad, "no puede ser mayor que el stock disponible (#{product.stock})")
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_one :payment
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  has_many :product_promotions
  has_many :promotions, through: :product_promotions
  has_many :reviews
  has_many :cart_items

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  def category_ids=(ids)
    self.product_categories = ids.map { |id| ProductCategory.new(category_id: id) if id.present? }.compact
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_promotion.rb
class ProductPromotion < ApplicationRecord
  belongs_to :product
  belongs_to :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :product_promotions
  has_many :products, through: :product_promotions
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :reviews
  has_many :cart_items

  # Roles de usuario
  ROLES = %w[admin registered guest client]

  validates :role, inclusion: { in: ROLES }, allow_nil: true

  # Métodos de conveniencia para verificar el rol
  def admin?
    role == 'admin'
  end

  def registered?
    role == 'registered'
  end

  def guest?
    role == 'guest'
  end

  def client?
    role == 'client'
  end
end

app/controllers/product_promotions_controller.rb
class ProductPromotionsController < ApplicationController
  before_action :set_product_promotion, only: %i[ show edit update destroy ]

  # GET /product_promotions or /product_promotions.json
  def index
    @product_promotions = ProductPromotion.all
  end

  # GET /product_promotions/1 or /product_promotions/1.json
  def show
  end

  # GET /product_promotions/new
  def new
    @product_promotion = ProductPromotion.new
  end

  # GET /product_promotions/1/edit
  def edit
  end

  # POST /product_promotions or /product_promotions.json
  def create
    @product_promotion = ProductPromotion.new(product_promotion_params)

    respond_to do |format|
      if @product_promotion.save
        format.html { redirect_to @product_promotion, notice: "Product promotion was successfully created." }
        format.json { render :show, status: :created, location: @product_promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_promotions/1 or /product_promotions/1.json
  def update
    respond_to do |format|
      if @product_promotion.update(product_promotion_params)
        format.html { redirect_to @product_promotion, notice: "Product promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @product_promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_promotions/1 or /product_promotions/1.json
  def destroy
    @product_promotion.destroy

    respond_to do |format|
      format.html { redirect_to product_promotions_path, status: :see_other, notice: "Product promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_promotion
      @product_promotion = ProductPromotion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_promotion_params
      params.require(:product_promotion).permit(:product_id, :promotion_id)
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/product_promotions_helper.rb
module ProductPromotionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_promotions/_form.html.erb
<%= form_with(model: product_promotion) do |form| %>
  <% if product_promotion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_promotion.errors.count, "error") %> prohibited this product_promotion from being saved:</h2>

      <ul>
        <% product_promotion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :promotion_id, style: "display: block" %>
    <%= form.text_field :promotion_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_promotions/_product_promotion.html.erb
<div id="<%= dom_id product_promotion %>">
  <p>
    <strong>Product:</strong>
    <%= product_promotion.product_id %>
  </p>

  <p>
    <strong>Promotion:</strong>
    <%= product_promotion.promotion_id %>
  </p>

</div>

app/views/product_promotions/edit.html.erb
<h1>Editing product promotion</h1>

<%= render "form", product_promotion: @product_promotion %>

<br>

<div>
  <%= link_to "Show this product promotion", @product_promotion %> |
  <%= link_to "Back to product promotions", product_promotions_path %>
</div>

app/views/product_promotions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product promotions</h1>

<div id="product_promotions">
  <% @product_promotions.each do |product_promotion| %>
    <%= render product_promotion %>
    <p>
      <%= link_to "Show this product promotion", product_promotion %>
    </p>
  <% end %>
</div>

<%= link_to "New product promotion", new_product_promotion_path %>

app/views/product_promotions/new.html.erb
<h1>New product promotion</h1>

<%= render "form", product_promotion: @product_promotion %>

<br>

<div>
  <%= link_to "Back to product promotions", product_promotions_path %>
</div>

app/views/product_promotions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_promotion %>

<div>
  <%= link_to "Edit this product promotion", edit_product_promotion_path(@product_promotion) %> |
  <%= link_to "Back to product promotions", product_promotions_path %>

  <%= button_to "Destroy this product promotion", @product_promotion, method: :delete %>
</div>